name: Android CI/CD

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Update the Java version to 17
          distribution: 'adopt'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: 'success'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Linting
        run: ./gradlew lintDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Release APK
        uses: actions/download-artifact@v2
        with:
          name: release-apk
          path: app/build/outputs/apk/release/

      - name: Deploy to Google Play Store
        # Add your deployment script or command here
        # For example, you can use a tool like fastlane or gradle-play-publisher to deploy to the Play Store
        run: |
          echo "Deploying release APK to Google Play Store..."
          # Your deployment command goes here

